### ISSUE TITLE
I don't know how to package the project

### ISSUE THREAD

**Issue by juanhima1** [paradajz/OpenDeckUI#1]
I have made few changes in the project, mainly translating texts. It works fine using "yarn dev". 
I open Chrome and I can view my changes in "localhost:3002"
I'm trying to package the project with "yarn electron-packager . OpendeckConfigurator --overwrite --platform=win32 --arch=x64" but when I execute OpendeckConfigurator.exe and the window shows nothing. I used CTRL-SHIFT-I to show the problem. I saw that "index.html" couldn't find the file "main.ts". I solved this problem changing "<script type="module" src="/src/main.ts"></script>" for "<script type="module" src="./src/main.ts"></script>"
I have packaged the project again, and still is not working. This time. the error showed in the windows of the OpenDescConfigurator refering to the "main.ts", is:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "video/vnd.dlna.mpeg-tts". Strict MIME type checking is enforced for module scripts per HTML spec."

I haven't made changes in files like "main.js", "main.ts", "tsconfig.json", "package.json".
To be sure, I downloaded [202306291358](https://github.com/shanteacontrols/OpenDeckUI/releases/tag/202306291358) again. I tried to package and the result was the same. I had to correct "index.html" and finally I get the same problem.

I'm sure that I'm doing something wrong but I have no idea what.

Any suggestions?
Thanks

**Comment by juanhima1** [comment]
I have written the same problem in other place on OpenDeckUI. 
Sorry.... I'm new on this site.

**Comment by juanhima1** [comment]
Sorry. I don't know where the correct place to open the issue. I'm new on this site

**Comment by pmjcontroller1** [comment]
hello, it seems that the place is the right one, they usually respond very quickly @paradajz  I do not know what's going on

**Comment by paradajz** [comment]
See https://github.com/shanteacontrols/OpenDeckUI/blob/master/.github/workflows/deploy.yml#L53

**Comment by juanhima1** [comment]
I was watchig the file you told me but I'm still not knowing what to do. 
It seems to be linux commands.
I'm using Visual Studio Code on Windows 10.
Should I install a extension on it?
I just want to pack the project and get an OpendeckConfigurator.exe file to execute on Windows.

Please, I just need a little help.
Thanks

**Comment by paradajz** [comment]
Sorry, I don't use nor support Windows for any kind of OpenDeck development.

**Comment by juanhima1** [comment]
I have installed Linux 18.04.6 LTS
I have installed nodejs v 14.21.3 and npm v 6.14.18
I downloaded https://github.com/shanteacontrols/OpenDeckUI/releases/tag/202306291358 release again.
I did npm init and npm install
Problems;
- yarn dev doesn't work: ERROR: [Errno 2] No such file or directory: 'dev'
- The only way to start de app in development mode is: **npm run dev**
- I have packaged the app with: "npx electron-packager . OpendeckConfigurator --overwrite --platform=win32 --arch=ia32. The result was an OpendeckConfigurator.exe. I copied the file in a windows machine and the result was the same that my first comment refering to the main.ts file: 

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/vnd.dlna.mpeg-tts". Strict MIME type checking is enforced for module scripts per HTML spec.
- The error is similar if I execute "**npm start dev**" in the Linux machine
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/vnd.trolltech.linguist". Strict MIME type checking is enforced for module scripts per HTML spec.

Please, can you tell me what I have to do in order to get an OpendeckConfigurator.exe file as you have in your Realease Section?
I really appreciate if you can tell me what to do step by step,

Thanks

![image](https://github.com/shanteacontrols/OpenDeckUI/assets/141143620/6bdd5e5f-f7c4-47a1-b397-d24e39b5ddb5)

**Comment by paradajz** [comment]
I have now added the ability to run the development environment for this project in a Docker container. Check the README for more info.
